import React, { Fragment } from "react";

const ShowLogoMovie = () => {
  return (
    <Fragment>
      <li className="nav-item">
        <a
          className="nav-link"
          id="v-pills-home-tab"
          data-toggle="pill"
          href="#BHDStar"
          role="tab"
          aria-controls="v-pills-home"
          aria-selected="true"
        >
          <img
            src="https://movie0706.cybersoft.edu.vn/hinhanh/cgv.png"
            alt=""
            width="100%"
          />
        </a>
        <a
          className="nav-link"
          id="v-pills-home-tab"
          data-toggle="pill"
          href="#BHDStar"
          role="tab"
          aria-controls="v-pills-home"
          aria-selected="true"
        >
          <img
            src="https://movie0706.cybersoft.edu.vn/hinhanh/cgv.png"
            alt=""
            width="100%"
          />
        </a>
        <a
          className="nav-link"
          id="v-pills-home-tab"
          data-toggle="pill"
          href="#BHDStar"
          role="tab"
          aria-controls="v-pills-home"
          aria-selected="true"
        >
          <img
            src="https://movie0706.cybersoft.edu.vn/hinhanh/cgv.png"
            alt=""
            width="100%"
          />
        </a>
        <a
          className="nav-link"
          id="v-pills-home-tab"
          data-toggle="pill"
          href="#BHDStar"
          role="tab"
          aria-controls="v-pills-home"
          aria-selected="true"
        >
          <img
            src="https://movie0706.cybersoft.edu.vn/hinhanh/cgv.png"
            alt=""
            width="100%"
          />
        </a>
        <a
          className="nav-link"
          id="v-pills-home-tab"
          data-toggle="pill"
          href="#BHDStar"
          role="tab"
          aria-controls="v-pills-home"
          aria-selected="true"
        >
          <img
            src="https://movie0706.cybersoft.edu.vn/hinhanh/cgv.png"
            alt=""
            width="100%"
          />
        </a>
      </li>
    </Fragment>
  );
};

export default ShowLogoMovie;
